sudo: false

language: c

arch: ppc64le

compiler:
  - gcc
  - clang

addons: &addons
  apt:
    packages:
      - libusb-dev

matrix:
  include:
    - compiler: gcc
      if: (branch = master) AND (type != pull_request)
      env:
        - secure: "JdUp+xFykPZoYA4aRfmYk2CtilLapniQllWPKo2dDdJd1vzdawfTvVxIAKjy7ac9RKwZzg3Chq3RsMEXPv8BtaLbssw266C7RDLMgjacl1eFLcmGRj/Gkk9peDSZ6vVdGEcA2j+6KDSfpCa/XjFjvOufZOgKw6m+3+d0A4G45SI="
      addons:
        <<: *addons
        coverity_scan:
          project:
            name: "pali/0xFFFF"
            description: "Build submitted via Travis CI"
          notification_email: quty@gmail.com
          build_command: make
          branch_pattern: master

script:
  - if [ -n "$COVERITY_SCAN_TOKEN" ]; then exit 0; fi
  - make
